### ISSUE TITLE
Cloud you let me know the version of python and cuda?

### ISSUE THREAD

**Issue by ibkuroyagi** [wilkinghoff/icassp2023#1]
I would like to reproduce your code, but I am unable to execute it due to errors related to TensorFlow and Keras. 
Therefore, I kindly request you to provide information about the specific environment in which your code was tested and successfully executed. 
This information will greatly help me in resolving the issues I am currently facing. 
Thank you for your understanding and support.

**Comment by wilkinghoff** [comment]
Thank you for your interest. I used Python 3.6.5 and CUDA 10.1.

**Comment by wyk777777** [comment]
Is the directory structure of the dataset different from the official one?
<img width="270" alt="image" src="https://github.com/wilkinghoff/icassp2023/assets/129475092/fb412c36-86ef-448b-96bc-529faea608f5">

**Comment by wilkinghoff** [comment]
I did not use any "processed" or "raw" folders and just placed the folders for the machine types directly in "dev_data" or "eval_data". But other than that, it looks fine to me. But you can also simply adjust the paths in the script.

**Comment by wyk777777** [comment]
Thank you very much for helping me answer my questions
