### ISSUE TITLE
The csv file for the evaluation dataset y_true could not be found

### ISSUE THREAD

**Issue by zxj11zxj11zxj11** [wilkinghoff/icassp2023#3]
Thank you for your meaningful work.Could you tell me how the.csv file of line 524 of the code was obtained, I cannot find this file.
![image](https://github.com/wilkinghoff/icassp2023/assets/127805303/80f9883e-d5fd-4d5d-b8d1-2c1035fb3269)

**Comment by wilkinghoff** [comment]
Thank for pointing this out. The labels for the evaluation set can be found here: https://github.com/Kota-Dohi/dcase2022_evaluator

**Comment by zxj11zxj11zxj11** [comment]
Thank you very much for helping me answer my questions.
